version: "3.8"

services:
  gnmd-nginx:
    container_name: gnmd-nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"
    depends_on:
      - gnmd-php-fpm
    restart: unless-stopped

  gnmd-php-fpm:
    container_name: gnmd-php-fpm
    build:
      context: .
      dockerfile: docker/php/8.2/fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - gnmd-mysql

  gnmd-php-cli:
    container_name: gnmd-php-cli
    build:
      context: .
      dockerfile: docker/php/8.2/cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - gnmd-mysql

  gnmd-mysql:
    container_name: gnmd-mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - gnmd-mysql-db-data:/bitnami/mysql/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: gnmd-network

volumes:
  gnmd-mysql-db-data:
